### ISSUE TITLE
Commit 0d6f691 has broken Season/Champion references

### ISSUE THREAD

**Issue by ShoobyDoo** [ShoobyDoo/OPGG.py#7]
The recent "cacher overhaul and common summoner methods complete" commit has broken Champion/Season lookup logic because instead of pinging out to op.gg for the pageprops that contain said champions/seasons information, we pull from cache and that request never goes out.

This will be addressed/fixed in the full 1.3.0 release, where I decided to just cache both the champions and seasons as these datasets do not regularly change and I'll just end up doing a request out each time I see a champion object nulled. (Name=None), this way itll only request out for the data when it needs to.

**Comment by Endermaiter** [comment]
Hello ShoobyDoo!

My name is Marcos and im currently programming my own discord bot using your code to scrap data from OP.GG.. But i have found the bug reported on this issue:


![Image](https://github.com/ShoobyDoo/OPGG.py/assets/91609087/e7473603-3358-48f0-b725-1b6fc94081b1)

I would like to use your code to my personal proyect but this bug is a blocking point. Do you know when are ging to launch v1.3.0 release officially? Or at least, please, tell me how can i do a workarround or temporally fix on code.

Thank you!

**Comment by ShoobyDoo** [comment]
Hey there @Endermaiter,

Thank you for using opgg.py!

Do you mind joining the support [discord](https://discord.gg/fzRK2Sb)? If you're available at the moment, I'd like to help troubleshoot some things.

I just fired up a fresh Windows 11 sandbox and tried using opgg.py 1.2.0 directly from pip and all seems well still.
This commit comment was specifically for the main branch, you might have issues if you cloned directly instead of using pip.

I will try to restructure the branches (probably main vs dev) so that in the future things will be stable even for users cloning the repo directly.

**Comment by ShoobyDoo** [comment]
commit [fc55acc](https://github.com/ShoobyDoo/OPGG.py/commit/fc55acc818870060d3ae9a52e32a53e524d1e530) closes this.
